function aboutController($scope) {
  $scope.staff = [
    {
      name: 'Patricia Santas',
      img: 'img/therapist/patricia.jpg',
      edu: 'BA, LMT, Owner',
      education: ['BA VSU 2000', 'LMT Core Institute 2002'],
      discount: '$15',
      discounts: ['Seniors (80+ years)'],
      bio: 'Patricia’s approach to massage therapy is rooted in a deep understanding of Western anatomy and physiology, while also being grounded in the Eastern tradition of mindfulness. Her passion for this work began through her own experience navigating generalized anxiety and panic attacks. At just thirteen years old, Patricia discovered the grounding power of scalp massage—a moment that revealed, on a core level, the profound healing potential of intentional touch. Today, she strives to support each client in achieving soft tissue balance in the body, while also nurturing a clear mind and an open heart.\n\nPatricia values the importance of living intentionally and brings that same mindfulness into her massage practice. Outside the office, she finds joy in spending time with her family and grandchildren, often keeping a full and vibrant schedule. Her peaceful morning walks are a cherished routine, helping her stay grounded and balanced—qualities she carries into every session with her clients.',
      license: 'MT001891'
    },
    {
      name: 'Ari Santas',
      img: 'img/therapist/ari.png',
      edu: 'PhD, LMT',
      education: ['PhD Philosophy Florida State University 1989', 'LMT Core Institute 2002'],
      discount: '$10',
      discounts: ['VSU faculty, students, and staff', 'Teachers'],
      bio: 'Massage offers both client and therapist a shared space of focus, balance, and awareness—an opportunity to engage deeply with the movement and function of the body. Ari views massage therapy as a practice in self-awareness and a step toward greater independence in maintaining one’s body-mind health.\n\nWhether he is working with an athlete in training or someone seeking relief from chronic pain, his goal is to help clients develop a clearer understanding of what’s happening in their bodies—both in the areas needing immediate attention and within the body as a dynamic, interconnected whole. That awareness often becomes the first step toward relaxation, relief, and sustainable self-care.\n\nAri emphasizes the interplay between mind and body, particularly how thoughts can manifest as muscular contraction—how repetitive, unresolved thinking may lead to chronic tension and somatic dysfunction. In every session, he aims to share what he observes and offers exercises or movement practices to those clients who wish to participate actively in their own healing and ongoing well-being.',
      license: 'MT002654'
    },
    {
      name: 'Pamela Johnson',
      img: 'img/therapist/pamela.jpg',
      edu: 'MJ, BA, Office Admin Assisrant & Mindfully Made Product Manager',
      education: ['MJ University of Tulsa College of Law 2017', 'BA Philosophy & Religious Studies, VSU 2013'],
      bio: 'Pamela plays a vital role behind the scenes, handling many of the administrative duties with care and precision that keep the office running smoothly. With a background in law and a strong interest in staying current with state and federal regulations, she helps ensure the business operates smoothly and responsibly—providing a safe, professional, and welcoming space for all clients seeking therapeutic massage and bodywork.\n\nPamela’s deep interest in the field of massage and the power of healing through intentional touch has inspired her next step, beginning massage therapy school in the near future. With a nurturing spirit and a love for all things rooted in care, she’s often found tending to the flowers and trees around the business grounds.  Gardening is not just a hobby but a passion that mirrors her belief in natural healing and growth. When she’s not in the office or the garden, she finds peace and grounding in the quiet company of her chickens and cats, who bring her joy and serenity in equal measure.',
    },
    {
      name: 'Robi Lin Boney',
      img: 'img/therapist/robi.png',
      edu: 'LMT',
      education: ['Florida School of Massage Sports Massage', 'Center For Neurosomatic Therapy'],
      bio: 'Robi is a seasoned massage therapist with over 20 years of hands-on experience in a diverse range of therapeutic and healing modalities. Her practice is deeply rooted in a commitment to injury treatment, rehabilitation, and long-term wellness. Robi specializes in therapeutic bodywork that integrates principles from chiropractic, orthopedic, and physical therapy disciplines, offering clients effective and results-driven care.\n\nIn addition to her advanced hands-on skills, Robi is passionate about educating clients on injury prevention and body mechanics, empowering them to take an active role in their recovery and well-being. Her dedication to both healing and education makes her a trusted resource for those seeking to recover, rebuild, and thrive.',
      license: 'MT013380',
    },
    {
      name: 'Darrell Lynch',
      img: 'img/therapist/darrell.jpg',
      edu: 'LMT',
      education: ['Florida School of Massage 2019'],
      bio: 'Darrell specializes in Swedish, deep tissue, myofascial massage, and neuromuscular therapy, using a thoughtful and therapeutic approach to help clients find balance, relief, and renewal. His journey into massage therapy began after experiencing its powerful benefits firsthand while recovering from an injury, sparking a deep passion for helping others heal.\n\nOutside of the treatment room, Darrell enjoys spending time on his small farm, where he finds peace tending to his beehives. The honey from his bees is harvested with care and available for purchase in our gift shop - a sweet testament to his care and dedication, both in his work and his daily life.',
      license: 'MT012881',
    },
    {
      name: 'Abby Voigt',
      img: 'img/therapist/abby.jpg',
      edu: 'LMT, HHP, RYT-200, CCP',
      education: ['San Diego Academy of Health Professions'],
      bio: 'With over 25 years of hands-on experience, Abby brings deep expertise and compassionate care to every session. Specializing in Swedish, Deep Tissue, Prenatal, Thai massage, and Reiki, she creates a safe, nurturing space where clients can relax, release, and reconnect with their natural capacity to heal.\n\nAbby\'s approach blends technical skill with intuitive touch, aiming not only to relieve physical tension but also to support emotional well-being. As a registered yoga instructor, she believes strongly in the healing power of movement. Her sessions reflect this philosophy, often incorporating mindful awareness and gentle encouragement toward self-care beyond the treatment room.\n\nWhether you\'re recovering from injury, navigating stress, or simply seeking balance, Abby\'s work is grounded in one mission: to help you feel whole—body, mind, and spirit.',
      license: 'MT013409',
    },
    {
      name: 'Brey Littleton',
      img: 'img/therapist/brey.jpg',
      edu: 'LMT',
      education: ['Center for Massage and Natural Health 2017'],
      bio: 'Brey brings a deeply intuitive and holistic approach to bodywork, specializing in Swedish, Deep Tissue, Myofascial Release, Neuromuscular Therapy, Lomi-Lomi, Sports massage, and Hot Stone massage, and more, blending these techniques to create a uniquely personalized and restorative experience for each client.  Utilizing modern and ancient techniques, Brey’s practice comes from a tangible fascination with energy work in all its forms alongside a solid foundation in the somatic sciences of massage and bodywork. His main specialization focuses in modalities derived from Traditional Chinese Medicine which aim to restore chi flow throughout the body, such as Acupressure and Reflexology.\n\nBrey blends everything he has learned and experienced into an integrative massage for the individual client and curates a unique experience which will be of the highest benefit for your health goals. Join Brey on your healing journey and see what individually curated massage and bodywork can do for you and your overall health goals.',
      license: 'MT012046',
    },
    {
      name: 'Leigh Johnson',
      img: 'img/therapist/leigh.jpg',
      edu: 'LMT',
      education: ['Wiregrass Technical College'],
      bio: 'Specializing in Swedish, deep tissue, NMT, and hot-cold stone massage, Leigh brings a personalized, relaxing approach to every session. Her goal is to help clients escape reality through focused, therapeutic touch tailored to their unique needs.\n\nInspired by a lifelong desire to help others and a background in the military, Leigh finds deep satisfaction in the way clients feel renewed and relaxed after each session. She describes deep tissue massage as her favorite technique, calling the release of built-up tension and stress “almost magical.” Leigh brings a grounded, compassionate presence to each session, with a strong foundation in therapeutic techniques and a genuine commitment to client well-being. She is passionate about continuing to grow in the field and is dedicated to helping clients feel heard, cared for, and restored.\n\nOutside of massage, Leigh recharges with bubble baths, naps, or massages of her own, and enjoys Krav Maga and crochet as creative outlets. She lives by the simple but powerful rule: Treat others the way you want to be treated.',
      license: 'MT015341',
    },
    {
      name: 'Mara Lamon',
      img: 'img/therapist/mara.jpg',
      edu: 'LMT',
      education: ['Wiregrass Technical College'],
      bio: 'Mara is a dedicated massage therapist with a focus on pain management and physically therapeutic treatments. She is passionate about helping clients manage chronic pain, identify areas of tension, and restore optimal function so they can feel and perform at their best. With a personalized approach to each session, she works to support long-term wellness and improved mobility.\n\nShe also enjoys participating in hospital wellness events, where she often spends hours providing chair massage to support healthcare workers and patients alike. Outside the treatment room, she enjoys spending quality time with family and friends, often relaxing with online games, gardening, and showering her beloved cats with affection.',
      license: 'MT013920',
    },
    {
      name: 'Shirley Rodgers',
      img: 'img/therapist/shirley.jpg',
      edu: 'Operations Manager and Senior LMT',
      education: ['Westside Technical College'],
      bio: 'With over 17 years of experience as a licensed massage therapist and more than two decades in the medical field, Shirley brings a deep well of knowledge, skill, and compassion to her work. Her background includes working closely with orthopedic surgeons, chiropractors, physical therapists, and even professional athletes—giving her a strong foundation in therapeutic, rehabilitative, and performance-based massage.\n\nShirley also has a heart for motherhood and women’s health. As a former birth assistant to a busy midwife practice, she has a unique perspective on prenatal and postnatal care, and she’s passionate about supporting mothers through all stages of pregnancy and recovery.\n\nHer love for sports and movement inspires her work, and her hands-on experience makes her a trusted partner for athletes and anyone on a healing journey. Shirley is committed to helping each client feel their best—whether they’re healing from injury, preparing for childbirth, managing pain, or simply in need of rest and renewal.\n\nIn addition to her hands-on work, she ensures the smooth daily operations of the building, bringing both skill and leadership to the heart of Mindful Massage & Bodywork. Outside the treatment room, Shirley is a proud wife to her husband, Jason, and a devoted mom to their four busy kids. You can often find her cheering from the sidelines, reading a good book, lounging in the pool, or snuggling with her two big (and lovable) dogs.',
      license: 'MT014809',
    },
    {
      name: 'Emma Rodgers',
      img: 'img/therapist/emma.jpg',
      edu: 'Receptionist',
      bio: 'Meet Emma, our friendly and energetic front desk receptionist! At just 16 years old, she balances her role at Mindful Massage & Bodywork with a full schedule as a dedicated high school student. Known for her warm smile and welcoming attitude, Emma helps keep the front desk running smoothly—whether she’s answering phones, checking in clients, or keeping things organized behind the scenes.\n\nWhen she’s not working or studying, Emma loves diving into a good book, catching up on sleep, and playing or watching baseball and softball. She’s also very active in several school clubs, where she’s always eager to take on new leadership roles and make a difference in her community. We’re lucky to have her as part of our team!',
    },
  ];
}
